name: absurd_starter
description: A Dart server starter using Netto, HTMX, hyperscript, Tailwind, Basecoat, and htmleez.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.0

dependencies:
  archive: ^4.0.7 # Used in order to generate the Lucide icons

  hotreloader: ^4.4.0
  htmleez: ^1.0.0
  netto: ^0.1.5

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
